<a href="https://colab.research.google.com/github/robertosgpontes/tec_prog_1/blob/main/ExerciciosNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [2]:
import numpy as np

# random.randint(low, high=None, size=None, dtype=int)
# Retorna random integers do low (inclusivo) to high (exclusivo).

array_int = np.random.randint(1,101,100)

array_int_max = array_int.max()
array_int_min = array_int.min()
# np.random.randint(1,101,[3:3])

print(f'Array: {array_int}\n')
print(f'Maximo: {array_int_max}. \nMinimo: {array_int_min}' )

Array: [ 17  56  40  89  65  22   1  53  88  46  97  32   7  21  22  44  11  24
   6  60  45  83  58  63  71  37  87  17  43   4  78  70  94  35  46  85
  67  49  59  58  52  12  82  59  77 100  99  60  73  42  17  43  72  95
  54  64  73  66  45  15  27  82  46   2  25  84  50  85  66   1  60  80
  49  99  99  54  50  13  38  23  21  47  80  75  74  92  80  69  24  42
  67  19  47  58  50  48  97  54  80  34]

Maximo: 100. 
Minimo: 1


## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [3]:
def modulo_vetor(vetor):
    """
    Entrada:
    - vetor: lista ou np.array com valores numéricos representando o vetor
    # Converte a entrada para um np.array numpy
    """
    vetor = np.array(vetor)

    
    """
    Saída:
    - modulo: float representando o módulo do vetor
    """   
    # Calcula a norma euclidiana do vetor, que é equivalente ao módulo
    modulo = np.linalg.norm(vetor)
    
    return modulo

# Exemplo de uso
vetor = [3, 4]
mod = modulo_vetor(vetor)
print("Módulo do vetor", vetor, "é", mod)

Módulo do vetor [3, 4] é 5.0


## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

In [12]:
# Solução

def calculate_eqm(y_prediction,y_i):

    """
    Entrada:
    - y_i: lista ou np.array com valores numéricos representando os valores reais
    - y_prediction: lista ou np.array com valores numéricos representando os valores previstos

    """
    diferenca_quadrado = (y_prediction - y_i)**2 


    """
     Saída:
    - eqm: float representando o erro quadrático médio
    """
    #mean() retorna a média dos elementos do array
    eqm = np.mean(diferenca_quadrado)

    return eqm


# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
eqm = calculate_eqm(y_prediction,y_i)

print("EQM:", eqm)

EQM: 1.6666666666666667


## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [2]:
def matriz_borda1 (linha,coluna):

    # Criando o array 2D com zeros
    matriz = np.zeros((linha, coluna), dtype=int)

    # Adicionando 1 na borda
    #linha 0 = 1
    matriz[0, :] = 1

    #linha n = -1, lendo invertido por nao saber qual é a última linha
    matriz[-1, :] = 1

    #coluna 0 = 1
    matriz[:, 0] = 1

    #coluna n = -1, lendo invertido por nao saber qual é a última linha
    matriz[:, -1] = 1

    return matriz

print('Matriz: \n', matriz_borda1(5,5)) #criando matriz 5,5

Matriz: 
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [9]:
# Define o array 2D existente
arr = np.array([[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]])

# Pega o tamanho do array em duas dimensões (linhas e colunas)
linha, coluna = arr.shape

# Adiciona uma borda de 0's ao redor do array, criando um novo array com dimensões aumentadas em 2
new_arr = np.zeros((linha + 2, coluna + 2))

# Copia os valores do array antigo para o novo array, exceto a borda de 0's
new_arr[1:-1, 1:-1] = arr

# Mostra o novo array com a borda adicionada
print(new_arr)




[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4. 5. 0.]
 [0. 5. 6. 7. 8. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

In [17]:
# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões

(64, 512)

In [18]:
# Solução
def process_EEG_signal(X):
  media = X.sum()/X.size
  print(f'Media: {media}')
  X_process = X - media
  return X_process

In [19]:
# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape

Media: 0.000327539087704898


(64, 512)

In [20]:
# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()

-10.732800825914117

In [21]:
# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X

array([[-0.98525699, -0.69710577,  0.3078516 , ..., -1.46265342,
        -1.2710214 ,  0.03871142],
       [-0.06570074, -0.26029632,  0.81533883, ..., -0.41602627,
         1.46516154,  0.33428376],
       [-0.84773397, -0.27050848, -0.53113784, ..., -0.2463862 ,
         0.44690045,  0.73076862],
       ...,
       [ 0.61913957,  1.38014861, -0.83406917, ...,  0.600478  ,
         1.2019985 ,  1.10386233],
       [ 0.07580871, -0.89978115, -0.27513194, ..., -1.86560031,
        -0.73768792, -0.10750238],
       [ 0.54163052, -0.01224689, -1.80742295, ..., -0.64060791,
        -0.59643135, -1.948486  ]])

In [22]:
# Matriz após o processamento descrito no enunciado
X_processado

array([[-0.98558453, -0.69743331,  0.30752406, ..., -1.46298096,
        -1.27134894,  0.03838388],
       [-0.06602828, -0.26062386,  0.81501129, ..., -0.41635381,
         1.46483401,  0.33395623],
       [-0.84806151, -0.27083602, -0.53146538, ..., -0.24671374,
         0.44657291,  0.73044108],
       ...,
       [ 0.61881203,  1.37982107, -0.83439671, ...,  0.60015046,
         1.20167096,  1.10353479],
       [ 0.07548117, -0.90010869, -0.27545948, ..., -1.86592785,
        -0.73801546, -0.10782991],
       [ 0.54130298, -0.01257443, -1.80775049, ..., -0.64093545,
        -0.59675889, -1.94881354]])

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo de 1.5*IQR - Q1, ou acima de 1.5*IQR + Q3.

<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

In [24]:
def locate_outliers (matriz):
    #calculando primeiro e terceiro quartil
    q1 = np.quantile(matriz, 0.25)
    q3 = np.quantile(matriz,0.75)

    #calculando limite inferior e limite superior
    limite_inferior = q1 - 1.5 * (q3 - q1) 
    limite_superior = q3 + 1.5 * (q3 - q1)

    #valores fora do intervalo, retornando como boleano 
    is_outlier = np.where(((matriz > limite_inferior) & (X < limite_superior)), True, False)
    outliers = matriz[is_outlier]

    #calculando a quantidade de outliers
    outliers_count = np.sum(is_outlier)

    return is_outlier,outliers_count,outliers

In [30]:
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

array([[-1.11559043, -0.7966184 ,  1.07842926, ...,  1.11541582,
         0.52188018,  0.32150799],
       [-0.08532145, -1.09974544, -0.20186545, ...,  2.14999646,
         0.66798454,  0.54731004],
       [-1.14078859,  0.49203989, -0.24228148, ...,  0.08267418,
         0.43958562, -0.41236151],
       ...,
       [-0.69418242, -1.7031526 ,  0.2481907 , ...,  0.08279583,
         0.22252991,  0.32304233],
       [ 0.46962599, -0.63055041,  0.55935073, ...,  0.28110429,
        -0.79323742, -0.34869987],
       [ 1.80166294,  1.32902108, -1.64796065, ...,  1.60645226,
         0.56538535, -1.22978916]])

In [31]:
# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

In [32]:
is_outlier

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [33]:
outliers_count

4472

In [34]:
outliers

array([-1.11559043, -0.7966184 ,  1.07842926, ...,  1.60645226,
        0.56538535, -1.22978916])

## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [8]:
vetor_arange = np.arange(1, 21+1, 2)

print(vetor_arange)

[ 1  3  5  7  9 11 13 15 17 19 21]


## Questão 9

Crie um array de 10 com valores aleatórios

In [7]:
vetor_aleatorio = np.random.random(10)

vetor_aleatorio

array([0.21707426, 0.27224655, 0.28821895, 0.62683361, 0.07390724,
       0.30098339, 0.72331738, 0.51404582, 0.42693346, 0.87378429])

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [14]:
def normalizacao(x):
    #media
    media = np.mean(x)

    #desvio padrao
    desvio_padrao =  np.std(x)

    #normalizacao
    norm = (x - media)/desvio_padrao
    
    return norm

In [15]:
Inicio = 54
Fim = 15
arr = np.random.rand(100)*(Fim-Inicio) + Inicio
norma = normalizacao(arr)
norma

array([ 1.2399426 ,  1.18825491,  0.17409927, -1.35555901, -0.58836676,
        0.21626353, -1.71983039, -0.09372741,  1.64802187,  0.40543201,
       -1.55740082, -1.46174128, -1.35075892, -1.45515274,  0.34205036,
       -0.01833792,  0.49899881, -0.80009738, -0.6787997 , -0.36975705,
        0.08968909,  1.03717582, -0.04147122, -0.13738304,  1.27697459,
       -0.26168124,  0.50376995,  0.85809327, -1.70994726,  0.07867383,
       -0.3925104 ,  1.23102909,  0.29143488,  1.54515187,  0.95339639,
       -0.61974437, -0.81093693, -1.27619554,  1.16329241,  0.70545698,
        0.84834519, -0.57668707, -0.74401408, -0.27595872, -1.5411283 ,
        0.75747507, -0.89424608, -1.11699776, -1.42074861,  1.77164927,
       -0.96117793,  1.63821471, -0.58001934,  1.23128157,  0.8688726 ,
       -0.28083111, -0.70255593, -0.86213368,  1.19210741, -1.22899252,
        0.74865639, -1.00329166, -1.20523038, -0.43457366, -1.54521478,
        1.60722756,  1.775521  ,  0.27344859,  0.21901934, -0.27

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [29]:
def notas_alunos(notas):
    media_notas = np.mean(notas)
    desvio_notas = np.std(notas)
    maior_que_sete = np.size(notas[notas > 7])
    reprovado = np.size(notas[notas < 5])
    menor_nota = notas.min()
    maior_nota = notas.max()

    return np.array([media_notas,desvio_notas,maior_que_sete,reprovado,menor_nota,maior_nota])

In [31]:
#gerar números aleatórios e multiplicá-los por 10 para que sejam números entre 0 e 10.
aleatorio_100 = np.random.rand(100)*10

print(aleatorio_100)

notas_alunos(aleatorio_100) 

[8.30837708 1.09633083 5.26330814 7.98324607 6.06659722 4.4166877
 8.85941231 5.37558413 0.92372148 9.56678524 7.35550811 5.69781893
 3.50400252 5.3447835  7.37272683 7.92458463 0.3291006  7.05593381
 3.14026961 0.88849626 9.30067696 8.01740769 9.58499262 1.34160723
 9.31052489 8.4875372  9.37039466 0.3230514  7.11989314 2.28885244
 5.62084344 0.73096501 4.29016498 1.90794496 1.8782425  9.29049861
 8.61416023 4.11878641 3.55564238 3.29599718 3.78730707 8.9838363
 9.54636517 7.36223403 6.35375504 5.7288345  8.70141941 2.90312161
 6.07887542 0.60100141 7.67390203 4.16565015 3.13002003 9.56294484
 3.52415736 4.26645507 7.61617476 9.6631289  0.59629867 3.93557251
 3.49641896 1.38028714 6.24087843 6.44509912 3.19269822 0.6736166
 4.04593971 1.45895328 5.49904495 5.64666656 2.59434005 2.54779955
 4.09094937 6.65855405 2.65769681 6.99330263 0.82102587 4.86102801
 0.70540504 3.5009072  8.2594701  8.82839979 8.74407295 3.93811377
 5.58750161 4.56569147 3.59239873 1.69286733 9.8065279  9.6549332

array([ 5.13708095,  2.83113798, 31.        , 50.        ,  0.15071629,
        9.8065279 ])